apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-native-framework
  labels:
    app: agent-native-framework
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agent-native-framework
  template:
    metadata:
      labels:
        app: agent-native-framework
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: agent-native-framework
      containers:
      - name: agent-manager
        image: agent-native-framework:latest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8000
          name: metrics
          protocol: TCP
        env:
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: agent-secrets
              key: anthropic-api-key
        - name: LOG_LEVEL
          value: "INFO"
        - name: MAX_CONCURRENT_AGENTS
          value: "8"
        - name: ENABLE_METRICS
          value: "true"
        - name: METRICS_PORT
          value: "8000"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        volumeMounts:
        - name: agent-config
          mountPath: /app/config
          readOnly: true
        - name: agent-logs
          mountPath: /app/logs
      - name: metrics-exporter
        image: prom/node-exporter:latest
        ports:
        - containerPort: 9100
          name: node-metrics
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: agent-config
        configMap:
          name: agent-config
      - name: agent-logs
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - agent-native-framework
              topologyKey: kubernetes.io/hostname
      tolerations:
      - key: node.kubernetes.io/not-ready
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 300
      - key: node.kubernetes.io/unreachable
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 300